CREATE USER docker;
/*
CREATE DATABASE IF NOT EXISTS DISweden;
GRANT ALL PRIVILEGES ON DATABASE DISweden TO docker;
CREATE DATABASE DIFinland;
GRANT ALL PRIVILEGES ON DATABASE DIFinland TO docker;
CREATE DATABASE DINorway;
GRANT ALL PRIVILEGES ON DATABASE DINorway TO docker;
CREATE DATABASE DIEstonia;
GRANT ALL PRIVILEGES ON DATABASE DIEstonia TO docker;
CREATE DATABASE DIDenmark;
GRANT ALL PRIVILEGES ON DATABASE DIDenmark TO docker;
*/

SELECT 'CREATE DATABASE DISweden'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'DISweden')\gexec

SELECT 'CREATE DATABASE DIFinland'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'DIFinland')\gexec

SELECT 'CREATE DATABASE DINorway'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'DINorway')\gexec

SELECT 'CREATE DATABASE DIEstonia'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'DIEstonia')\gexec

SELECT 'CREATE DATABASE DIDenmark'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'DIDenmark')\gexec